### ISSUE TITLE
CardContainer.js refactoring from class to hooks

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/react-trello-clone#100]
https://github.com/bmarvinb/react-trello-clone/blob/master/src/features/board/containers/CardContainer.js

**Comment by Selharem** [comment]
Hi, can I take this one ?

**Comment by bmarvinb** [comment]
@Selharem yes, I Will assign you today

**Comment by Selharem** [comment]
Ok @bmarvinb, thanks!

**Comment by bmarvinb** [comment]
@Selharem assigned

**Comment by bmarvinb** [comment]
already done
