### ISSUE TITLE
CreateBoardModal.js refactoring from class to hooks

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/react-trello-clone#106]
https://github.com/bmarvinb/react-trello-clone/blob/master/src/features/boards/components/CreateBoardModal.js

**Comment by harshrai654** [comment]
Can I try this?

**Comment by bmarvinb** [comment]
@harshrai654 yes

**Comment by harshrai654** [comment]
This component is already a functional component with hooks, What refactoring is needed here?

**Comment by bmarvinb** [comment]
@harshrai654 task is outdated
