### ISSUE TITLE
PasswordForget.js refactoring from class to hooks

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/react-trello-clone#108]
https://github.com/bmarvinb/react-trello-clone/blob/master/src/auth/pages/PasswordForget.js

**Comment by Armakuji** [comment]
Can you assign this issue to me?

**Comment by Armakuji** [comment]
This issue is done ✨.Please check out PR : https://github.com/bmarvinb/react-trello-clone/pull/126
