### ISSUE TITLE
Improve 404 page

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/react-trello-clone#111]
Improve design of 404 page, try something like this 
![image](https://user-images.githubusercontent.com/23120972/135703570-b275aa1a-1ff5-47ea-8dc1-4f15e7eb00b0.png)

**Comment by wsameer** [comment]
@bmarvinb  If you can provide the resources/assets needed then I can take this up.

Also, would be nice if you add a `hacktoberfest` topic to your repo, since that'll give me more points.

**Comment by bmarvinb** [comment]
@wsameer no, this just an example, you can use assets that you likes

**Comment by Anas-hameed** [comment]
Hey there,
I would like to contribute towards this issue. Can you assign me this issue?
Thank You!

**Comment by bmarvinb** [comment]
@Anas-hameed assigned )
