### ISSUE TITLE
Change auth handling from HOC to context

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/react-trello-clone#112]
Replace it https://github.com/bmarvinb/react-trello-clone/blob/master/src/auth/utils/AuthHOC.js
Use new react context https://reactjs.org/docs/context.html

**Comment by harshrai654** [comment]
In this, I have to replace the old Context API with new use context hook right? if yes then i would like to work on this issue.

**Comment by harshrai654** [comment]
> In this, I have to replace the old Context API with new use context hook right? if yes then i would like to work on this issue.

I have tried changes can i make a PR for code review?

**Comment by bmarvinb** [comment]
@harshrai654 I will assign this task, create PR and I will look at it
