### ISSUE TITLE
Error while signing in with google

### ISSUE THREAD

**Issue by thesahindia** [bmarvinb/react-trello-clone#157]
**Describe the bug**
When you try to sign in with google the onSubmit function gets triggered and then inside catch setError runs and because the error.message is undefined we get an error.

**To Reproduce**

1. Go to 'Sign in page'
2. Click on 'Continue with google'
3. See error

**Screenshots**

![trelloError](https://user-images.githubusercontent.com/83179295/135849276-1e36ef5b-ddde-4dbe-a422-8e6484e4d79b.png)
**Suggestion**
- We can prevent the default behaviour of that "Continue with google" button so that it will not trigger the onSubmit.

**Comment by thesahindia** [comment]
@bmarvinb Let me know if I can send the PR.
Thanks.

**Comment by bmarvinb** [comment]
@thesahindia yes sure
