### ISSUE TITLE
[Refactoring] Import sorting

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/react-trello-clone#17]

**Comment by ShiviPro** [comment]
Hey @bmarvinb, could you please elaborate this issue ?

**Comment by bmarvinb** [comment]
@ShiviPro I want to sort every import with some order, for example first its 3rd party components, then custom code, and also we should separate it with an empty row. I'm super friendly to any PR

**Comment by ShiviPro** [comment]
Thanks for the clarification @bmarvinb . I will get started on this right away.

**Comment by ShiviPro** [comment]
Just to be super sure, @bmarvinb is it the import statements in all the JS files we are including for refactoring, or are there some that I need to exclude ? Also please clarify if we want to have the single empty row between each import or is it between each one of the categorized import groups of 3rd party code and custom code, and so on ? Would like to beg your pardon if I sound too explicit, I am new to open source contributions. Thanks for any help !

**Comment by bmarvinb** [comment]
@ShiviPro all js files, the rule is simple, lets sort imports by alphabet (in ideal), for example
`
import drag from 'react-dnd';
import React from 'react';
import * from 'lodash';

import Component from './components';
import OtherComponent from './components';
import Helper from './utils'
`

So we have 2 groups,  3rd party and our code

**Comment by ShiviPro** [comment]
Hey @bmarvinb , I was in middle of my modifications, when I encountered that there are list type imports with single as well as multiple items. One examples of these can be found in /src/core/routes/index.html, as follows - 
`
import { ACCOUNT, BOARD, BOARDS, LANDING, PASSWORD_FORGET, SIGN_IN, SIGN_UP } from './routes';
import { Navigation } from '../../navigation/Navigation';
`
Will the list with lesser entries have priority over multiple ones in this case or is this also alphabetical order of some sort ?

Also with multiple entries, do I sort each entry alphabetically, if not already done ?

Thanks for any help !

**Comment by bmarvinb** [comment]
@ShiviPro It is not so important as you think, make it simple, multiple imports its okay, but do not forget about prettier formatting. Scope of this work is very limited.

**Comment by bmarvinb** [comment]
You can skip sorting for multiple entries

**Comment by ShiviPro** [comment]
Hey @bmarvinb , I have made the necessary changes and made a pull request. Please have a look, whenever you can.
Thanks for helping throughout the course of this PR. Please feel free to recommend any improvements in the code that you want.

**Comment by bmarvinb** [comment]
@ShiviPro please resolve 2 conflict

**Comment by ShiviPro** [comment]
@bmarvinb , It shows something like this on the SignInForm.js - 
`import { Form, Icon, Input } from 'antd';
<<<<<<< ImportSorting#17
import React, { Component } from 'react';

import { BOARDS } from '../../core/routes/routes';
import { byPropKey } from '../../utils';
import { doSignInWithEmailAndPassword } from '../api/auth';
=======
import React, { useState } from 'react';
import { doSignInWithEmailAndPassword } from '../api/auth';
import { BOARDS } from '../../core/routes/routes';
// import { byPropKey } from '../../utils';
import { FormContainer } from './FormContainer';
>>>>>>> master
import { ErrorMessage } from './ErrorMessage';
import { FormButton } from './FormButton';
import { FormContainer } from './FormContainer';`
Am I to envelope all the contents under my branch name and master.  And what about the '====' notation. If you could please clarify, it would be great help. My apologies for bothering you so much. I am doing this for the first time.

**Comment by ShiviPro** [comment]
@bmarvinb , I have solved the conflicts. Had some issues with the notation originally, but Git documentation helped.

**Comment by bmarvinb** [comment]
@ShiviPro Merged 👍

**Comment by ShiviPro** [comment]
I would like to ask you, if I am a valid contributor now, or does it require some verification from your side. Anyways, I would like to thank you for your guidance as well as warm and welcoming attitude towards OSS contributors especially newcomers. It was great working on refactoring this project; Looking forward to contribute to other issues soon.

**Comment by bmarvinb** [comment]
Thanks, I will be glad to see you again
