### ISSUE TITLE
Feature. Custom input, buttons

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/react-trello-clone#190]
Use ant design input, button for column creation 
![image](https://user-images.githubusercontent.com/23120972/136506423-f59e2fc2-54d4-4e98-9671-2f583908529f.png)

And ant design button for card creation
![image](https://user-images.githubusercontent.com/23120972/136506463-af839f82-1528-49b4-a999-9a3f0b2d7e79.png)

**Comment by petoJ64** [comment]
Hi, I can try this. Can you assign me please?

**Comment by bmarvinb** [comment]
@petoJ64 what is the status?

**Comment by petoJ64** [comment]
@bmarvinb illl have it done tomorow. I work with react for first time so i have small problems.

**Comment by petoJ64** [comment]
@bmarvinb Im little bit lost. Where can i find components and html code for this page?

**Comment by bmarvinb** [comment]
@petoJ64 thanks for feedback
