### ISSUE TITLE
Feature. Delete board

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/react-trello-clone#191]
Add ability to delete board

**Comment by bmarvinb** [comment]
@mstofirova yes, assigned

**Comment by mstofirova** [comment]
so the deletion should not be on the page of the user's board similar to the lane and label but on the open board?

**Comment by bmarvinb** [comment]
![image](https://user-images.githubusercontent.com/23120972/136517393-69b50cee-205e-4b4f-9a44-f9737b37c096.png)

should be here, maybe at the right corner

**Comment by bmarvinb** [comment]
Also you can add title to this board, you already have this data in board
