### ISSUE TITLE
Redesign SignInPage/SignUpPage

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/react-trello-clone#194]
[forms.zip](https://github.com/bmarvinb/react-trello-clone/files/7315399/forms.zip)

Redesign sign page, use tailwind css, a lot of examples inside zip. I want to create split screen, on the left side form, on the right some image. Also I want to use joi + react hooks for data validation

**Comment by tabassum2507** [comment]
i would like to work on this.

**Comment by bmarvinb** [comment]
@tabassum2507 assigned

**Comment by bmarvinb** [comment]
@tabassum2507 what is the status?
