### ISSUE TITLE
Feature. Board validations

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/react-trello-clone#196]
Add some validation for lane creating, I do not want to create lane without title, it's required for any card. 
The same for card creating, card should contain title. 
Right now you can create lane and card without title, it's wrong

**Comment by tuanthanh2067** [comment]
I can work on this issue, can you please assign me this?

And can you please give me an account to test it out?

**Comment by bmarvinb** [comment]
@tuanthanh2067 assigned, what account do you mean?

**Comment by tuanthanh2067** [comment]
Like a demo account so that I can test features

**Comment by tuanthanh2067** [comment]
Because it seems like I can not create an account myself 

```
Firebase: The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section. (auth/operation-not-allowed).
```

**Comment by tuanthanh2067** [comment]
I'm using the config you provided in the `firebase.js` file but I keep
getting the same error when signing up!

**Comment by bmarvinb** [comment]
@tuanthanh2067 fixed

**Comment by tuanthanh2067** [comment]
Thank you, it's working now. Can you please assign this to me!

**Comment by bmarvinb** [comment]
@tuanthanh2067 ready

**Comment by tuanthanh2067** [comment]
I'm having trouble understand lane and card. Where can I find it?

**Comment by tuanthanh2067** [comment]
Actually, as I understand, react-trello doesn't support any method to prevent user from using empty string.

**Comment by tuanthanh2067** [comment]
But the thing is react trello doesn't have any way of doing that as far as I know!

**Comment by bmarvinb** [comment]
It possible. Just need to learn how

**Comment by tuanthanh2067** [comment]
I'm struggling with that, any help would be great

**Comment by bmarvinb** [comment]
@tuanthanh2067 i'm busy right now, all I can it's remove your assign and find another developer

**Comment by jaldipsuthar** [comment]
Hi @bmarvinb can you please share how did you resolved this issue? as I am also facing the same thing
