### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/react-trello-clone#21]
Add email validation for every email control

**Comment by amanverma-1001** [comment]
Do you need Continue with Google option? Can the access and refresh token be stored in local storage as of now?

**Comment by bmarvinb** [comment]
@amanverma-1001 I think it's a good idea, and it's easy to integrate with firebase, so you can try to implement it and create separate PR, its new feature, so you can create a separate issue for it.

**Comment by bmarvinb** [comment]
This task is only about client email validation, because now you can write something like "email@test" without any error, but it's wrong, it is not valid email
