### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/react-trello-clone#22]
Add public page for guest user (non-auth), start with home page, it can be a simple page with hero session, with beautiful picture and short text

**Comment by NikhilSharma03** [comment]
Please correct me if i am wrong
## Requirement
- Currenty the website starts with auth page (which is the home page for now)
- Need to add a new home page
- Home Page should contain Image and text and link to signup/signin.

**Comment by bmarvinb** [comment]
@NikhilSharma03  Hi, Hero section, not session, is a term from landing pages that mean first section in the page.
Access to the home page is only available to guests, if the user is already logged in, we must send him to the page with boards
If an unauthorized user tries to enter the page with boards we must send him to the login page, after successful login we redirect him to boards page

**Comment by NikhilSharma03** [comment]
Okay. I get it now. What kind of wallpaper should i use and also can you please assign this issue to me?

**Comment by bmarvinb** [comment]
Something like 
![image](https://user-images.githubusercontent.com/23120972/119378845-62fa0b80-bcc7-11eb-8977-603b5487b583.png)

**Comment by bmarvinb** [comment]
Assigned

**Comment by NikhilSharma03** [comment]
Thank you.

**Comment by bmarvinb** [comment]
@NikhilSharma03 What is the progress?

**Comment by NikhilSharma03** [comment]
@bmarvinb Thank you for the message. Actually, I am busy with my semester examination. You can assign this to someone else.
Sorry for the inconvenience.

**Comment by phoenixx1** [comment]
@bmarvinb  
I can give it a try, I'll create something and post an update by tomorrow.

**Comment by SpaceLobster2311** [comment]
Is this still available for work?

**Comment by bmarvinb** [comment]
@SpaceLobster2311 yes

**Comment by RanjithSivam** [comment]
My not so great design

![image](https://user-images.githubusercontent.com/57189095/132089637-2df5bf95-0d4c-4a8f-b6c5-5ec3dce6d4e7.png)

**Comment by bmarvinb** [comment]
Looks good. You create pr. And i Will review it in next weak

**Comment by ashu-11** [comment]
still open?

**Comment by bmarvinb** [comment]
@ashu-11 yes

**Comment by cyntler** [comment]
> My not so great design
> 
> ![image](https://user-images.githubusercontent.com/57189095/132089637-2df5bf95-0d4c-4a8f-b6c5-5ec3dce6d4e7.png)

I like your design! Provide please!
I hope, we can build something great together!

**Comment by RanjithSivam** [comment]
> > My not so great design
> > ![image](https://user-images.githubusercontent.com/57189095/132089637-2df5bf95-0d4c-4a8f-b6c5-5ec3dce6d4e7.png)
> 
> I like your design! Provide please!
> I hope, we can build something great together!

Thank you for the comments :D. But the design has changed.

![image](https://user-images.githubusercontent.com/57189095/134712014-fa000a73-d62b-4977-ba2f-0889acd60265.png)

This is the new image I am working on. It would be great if you could help me with this?

**Comment by cyntler** [comment]
> > > My not so great design
> > > ![image](https://user-images.githubusercontent.com/57189095/132089637-2df5bf95-0d4c-4a8f-b6c5-5ec3dce6d4e7.png)
> > 
> > 
> > I like your design! Provide please!
> > I hope, we can build something great together!
> 
> Thank you for the comments :D. But the design has changed.
> 
> ![image](https://user-images.githubusercontent.com/57189095/134712014-fa000a73-d62b-4977-ba2f-0889acd60265.png)
> 
> This is the new image I am working on. It would be great if you could help me with this?

That's nice too! What kind of help do you expect?

**Comment by RanjithSivam** [comment]
@cynter sorry for being late. Can you convert inline styles into separate sass file?
