### ISSUE TITLE
Continue with google option without writing email manually by users.

### ISSUE THREAD

**Issue by amanverma-1001** [bmarvinb/react-trello-clone#35]
The access token and refresh token provided by google can be stored in local storage which will be integrated to firebase later.

**Comment by phoenixx1** [comment]
@amanverma-1001 
You want signInWithPopUp or signInWithRedirect.
Also, do you have a docker for this project, as it works with only NodeJS 7.0.0 ?.
If not then I have to rollback to older version.

**Comment by bmarvinb** [comment]
@phoenixx1 I don't have docker, you can use nvm to select the older version of node.js

**Comment by phoenixx1** [comment]
@bmarvinb 
can you tell me how to do the same, I tried using nvm but the node version was changed instead of NodeJS.
Coding will not take long if you can help me with the installation of the previous version

**Comment by bmarvinb** [comment]
@phoenixx1 
"node version was changed instead of NodeJS"
What do you mean? Show the screenshot of your console, after "node -v"

**Comment by phoenixx1** [comment]
![image](https://user-images.githubusercontent.com/44865935/120799154-fcdd7600-c55b-11eb-95fe-4aca7f9d96c6.png)   
After that when I executed `npm i`
![image](https://user-images.githubusercontent.com/44865935/120799375-46c65c00-c55c-11eb-9dd5-5f197c194778.png)
   
I think maybe an issue with the version of npm, what is yours?

**Comment by phoenixx1** [comment]
@bmarvinb   
I can try to write the code directly and create a PR, you can run the same on your side, if there is any issue tell me.?

**Comment by bmarvinb** [comment]
@phoenixx1 try to use node version 7.0.0

**Comment by bmarvinb** [comment]
I need to update all react dependencies to update to the latest node, it can take a while, a don't have time right now for it. I will be happy, if someone can do this, for example, you. The project is small, and it should not take too much time.

**Comment by phoenixx1** [comment]
> I need to update all react dependencies to update to the latest node, it can take a while, a don't have time right now for it. I will be happy, if someone can do this, for example, you. The project is small, and it should not take too much time.

Alright, I fixed the issue, updated all the dependencies, now it is working with Node v15.14.0, I will complete the code soon and create a PR.

**Comment by phoenixx1** [comment]
q

> I need to update all react dependencies to update to the latest node, it can take a while, a don't have time right now for it. I will be happy, if someone can do this, for example, you. The project is small, and it should not take too much time.

Alright, I'll try to fix the issue, ant version will be giving many errors, I'll try to fix it and let you know.

**Comment by phoenixx1** [comment]
@bmarvinb   
Upgrading all dependencies resulted in more errors, coz then I have to change many imports and then new components required a new way of calling that I'm not very well aware of for all libraries.   
I'll write the code for login in some other project and then add it to yours then you can try directly.
Just tell me one thing in which file code is to be pasted.

**Comment by bmarvinb** [comment]
Use 7 version of node instead of 6. Should work well

**Comment by phoenixx1** [comment]
@bmarvinb    
Node v7 worked, I will post an update soon regarding the same.

**Comment by bmarvinb** [comment]
Remove node_modules, package json lock file, and then try to install again @phoenixx1

**Comment by phoenixx1** [comment]
@bmarvinb   
It worked anyway, I was able to start a local server.

**Comment by phoenixx1** [comment]
@bmarvinb   
I hope you have enabled the Google Login feature in firebase?

**Comment by bmarvinb** [comment]
@phoenixx1 Enabled this feature today

**Comment by phoenixx1** [comment]
@bmarvinb   

https://user-images.githubusercontent.com/44865935/120981410-4664d580-c795-11eb-9ae5-d567e2ed6a0c.mp4

**Comment by bmarvinb** [comment]
@phoenixx1 Please create pull request for your feature, and I will review it, and also run on my local machine

**Comment by phoenixx1** [comment]
@bmarvinb  #38   
Check it, created one.
