### ISSUE TITLE
Improve imports

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/react-trello-clone#42]
Improve imports by adding index.js file in every directory, then import all from subdirectories, and update all imports from this module, by details send me a message in the comments

**Comment by Adamchello** [comment]
Hi, i can do this issue. I have also seen that you are keeping css in a same file as the one with logic. I can divide files for example: create CardDescription.styles.js, where all styles will be and CardDescription.js where will be a component logic, to keep apart logic and styles.

**Comment by bmarvinb** [comment]
@Adamchello Hi, I will assign this task to you, I like your idea
