### ISSUE TITLE
Edit cards not working

### ISSUE THREAD

**Issue by marciobooi** [bmarvinb/react-trello-clone#46]
Hi my friend,
Very nice work
I try playing with your tool and I found that the edit cards isn’t working, just for let you know.
Also when you create a project it will be nice to add ability to change the color of the project.
When you drag and drop cards in the columns it will be nice some effect in the other cards, like the cards go up or down to the user see that if you drag the card will be at that place.
Keep rocking

**Comment by bmarvinb** [comment]
Thanks for the comment, added a few tags, maybe someone will want to fix this and create a pull request
