### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/react-trello-clone#56]
Update all available dependencies
- React
- React dnd
- Ant design
- etc...

**Comment by SarveshLimaye** [comment]
@bmarvinb would like to work on this issue.

**Comment by SarveshLimaye** [comment]
@bmarvinb Yeah I will try my best to resolve it .

**Comment by bmarvinb** [comment]
@SarveshLimaye  I make a lot changes, so please make update your repo

**Comment by bmarvinb** [comment]
@SarveshLimaye I updated react/react router, we should update antd, react-dnd, I don't like styled-components so we can skip this update, and in a future replace it with simple css

**Comment by SarveshLimaye** [comment]
@bmarvinb ok then  i will update antd,react-dnd and make pr

**Comment by SarveshLimaye** [comment]
@bmarvinb I am getting errors while installing npm packages

**Comment by bmarvinb** [comment]
@SarveshLimaye check your node version.

**Comment by bmarvinb** [comment]
Make sure is the same at the readme md file

**Comment by ashu-11** [comment]
Failed to load plugin 'import' declared in '.eslintrc » eslint-config-react-app': Cannot find module 'eslint'
 hey i am geeting this issuw when trying to run the project

**Comment by bmarvinb** [comment]
@ashu-11 @cyntler will look for this today, but if you can, you also can invest it

**Comment by ashu-11** [comment]
@bmarvinb  please raise it as a bug assigned it me I will try to solve

**Comment by bmarvinb** [comment]
@ashu-11 ready

**Comment by bmarvinb** [comment]
@ashu-11 please see https://github.com/bmarvinb/react-trello-clone/issues/85, https://github.com/bmarvinb/react-trello-clone/issues/84
