### ISSUE TITLE
Types with props

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/react-trello-clone#6]
Add types for props

**Comment by marooncoder09** [comment]
Is this issue still open..?
if yes then can I please work on it

**Comment by bmarvinb** [comment]
@marooncoder09 yes, I will assign this ticket to you

**Comment by marooncoder09** [comment]
Can you please elaborate on the work?

**Comment by bmarvinb** [comment]
A lot of components have props that we passed inside, but we should add props for it, to understand better what we passed. 
Here is article about it https://blog.logrocket.com/validating-react-component-props-with-prop-types-ef14b29963fc/
