### ISSUE TITLE
Missing package-lock file in project   .

### ISSUE THREAD

**Issue by saurabhmehta1601** [bmarvinb/react-trello-clone#62]
It is better to have a package-lock.json file in your project root ,  see why [here](https://medium.com/hackernoon/do-i-really-need-package-lock-json-file-321ce29e7d2c#:~:text=While%20working%20on%20a%20shared,dependency%20tree%20that%20you%20were) .
You can either generate `package-lock.json` by running command ` npm i --package-lock-only`  
 or `yarn install` to generate `yarn.lock`   from terminal in project root.

**Comment by bmarvinb** [comment]
Hi, yes this is good idea, and I don't know why I don't have it yet, I will add this soon

**Comment by bmarvinb** [comment]
Done
