### ISSUE TITLE
Fix console.log errors

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/react-trello-clone#63]
![image](https://user-images.githubusercontent.com/23120972/131833436-296b1898-43fd-46e6-ac17-65f1ad355aea.png)

**Comment by marooncoder09** [comment]
I want to work on this project

**Comment by bmarvinb** [comment]
Ok, I will assign this ticket to you

**Comment by bmarvinb** [comment]
@marooncoder09 what is the status?
