### ISSUE TITLE
Add form validation 

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/react-trello-clone#65]
Use https://react-hook-form.com/

**Comment by husain3012** [comment]
I would like to work on this

**Comment by bmarvinb** [comment]
@husain3012 ok

**Comment by husain3012** [comment]
I had some trouble running the app. npm install throws a bunch of errors. Something like "sh -c node-pre-gyp install --fallback-to-build --library=static_library" followed by a huge error log.
node version: 14.17.4
npm version:  7.21.1

**Comment by bmarvinb** [comment]
@husain3012 read readme.md please, and setup the same node version as it mentioned in readme.md, it is easy with "nvm" for example

**Comment by tenaureo** [comment]
hey, is this issue still open? if so, i'd like to work on it

**Comment by bmarvinb** [comment]
@tenaureo yes, you can
