### ISSUE TITLE
Create docker container for project

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/react-trello-clone#67]
We should add docker support to current project, so someone should create config, and test it! This will help other developers setup environment more quickly and easy, and you can learn a lot while implement it!

**Comment by cyntler** [comment]
@bmarvinb I can try! <3

**Comment by bmarvinb** [comment]
@cyntler done 👍 good luck

**Comment by cyntler** [comment]
@bmarvinb do you mean Docker support for development environment or for something like "production" (build & serve by nginx)?

**Comment by bmarvinb** [comment]
@cyntler first of all for Development.
