### ISSUE TITLE
Attention! Here you can write any issue/feature/refactoring idea

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/react-trello-clone#73]
A lot of people visit this repo every day, so I want to get feedback, and ideas from people, if you want something just create a comment with it, then we will create task, and assign someone, or maybe you, if you want it. I do not have time to develop further, but I can invest time to code review, and give you good feedback, so you can understand your problem. 

I'm not a guru in react, because my primary framework is Angular, but I know a lot of general good practices from software engineer, and can share my knowledge. 

I created this repo more than 3 years ago, and I didn't touch it for 3 years, but in last year it gain some starts and forks, so I make a lot of refactoring, and review a bunch of new code, I believe together we can develop it further and create good example of react project, that will help new developers to understand how to write good, but right know we need to complete a lot of work. 

Thanks for your attention!

p.s. do not forget to like this repo 🤙

**Comment by RanjithSivam** [comment]
I am getting this issue after the fetch request. Can you help me?
![Screenshot 2021-09-07 105541](https://user-images.githubusercontent.com/57189095/132289026-59fd1a21-fda4-43a7-8f8f-e4fd04d1e3d1.png)

**Comment by bmarvinb** [comment]
> I am getting this issue after the fetch request. Can you help me?
> ![Screenshot 2021-09-07 105541](https://user-images.githubusercontent.com/57189095/132289026-59fd1a21-fda4-43a7-8f8f-e4fd04d1e3d1.png)

Install this dependecy globally.

npm i eslint - g

**Comment by RanjithSivam** [comment]
> > I am getting this issue after the fetch request. Can you help me?
> > ![Screenshot 2021-09-07 105541](https://user-images.githubusercontent.com/57189095/132289026-59fd1a21-fda4-43a7-8f8f-e4fd04d1e3d1.png)
> 
> Install this dependecy globally.
> 
> npm i eslint - g

Didn't help. Same error

**Comment by bmarvinb** [comment]
> > > I am getting this issue after the fetch request. Can you help me?
> > > ![Screenshot 2021-09-07 105541](https://user-images.githubusercontent.com/57189095/132289026-59fd1a21-fda4-43a7-8f8f-e4fd04d1e3d1.png)
> > 
> > 
> > Install this dependecy globally.
> > npm i eslint - g
> 
> Didn't help. Same error

npm i eslint -g

-g without Space

**Comment by RanjithSivam** [comment]
> > > > I am getting this issue after the fetch request. Can you help me?
> > > > ![Screenshot 2021-09-07 105541](https://user-images.githubusercontent.com/57189095/132289026-59fd1a21-fda4-43a7-8f8f-e4fd04d1e3d1.png)
> > > 
> > > 
> > > Install this dependecy globally.
> > > npm i eslint - g
> > 
> > 
> > Didn't help. Same error
> 
> npm i eslint -g
> 
> -g without Space

Same error

**Comment by RanjithSivam** [comment]
I have a new error. I tried both:
npm i firebase -g
npm i firebase

![image](https://user-images.githubusercontent.com/57189095/132550795-62ffaf29-ba64-4472-9de7-eb3fd93c8c1c.png)

**Comment by bmarvinb** [comment]
I Will help you later. After12 september.

**Comment by bmarvinb** [comment]
@RanjithSivam bug is fixed
