### ISSUE TITLE
Docker error with eslint

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/react-trello-clone#77]
![image](https://user-images.githubusercontent.com/23120972/132985859-a82265b1-f175-46b9-9319-d0e4a07e3bf1.png)

Need to find a solution for this

**Comment by bmarvinb** [comment]
@cyntler Hi, can you look at it?

**Comment by cyntler** [comment]
@bmarvinb Deleting package-lock.json or node_modules does not work?

**Comment by bmarvinb** [comment]
@cyntler the same

**Comment by cyntler** [comment]
@bmarvinb I will check tomorrow.

**Comment by cyntler** [comment]
@bmarvinb https://github.com/bmarvinb/react-trello-clone/pull/82/files - fix probably.
