### ISSUE TITLE
Refactoring from class to function with hooks

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/react-trello-clone#78]
We should refactor all code with classes to functions, that use hooks for state

**Comment by gauraws** [comment]
@bmarvinb Can I take a look at this task? I my corporate firewall allow all npm nodules to be installed, I might be able to refactor few class components to function with hooks.

**Comment by bmarvinb** [comment]
@gauraws yes sure, I will assign it to you

**Comment by gauraws** [comment]
Raised PR #93 , Please review
