### ISSUE TITLE
Live iisue during registration

### ISSUE THREAD

**Issue by ashu-11** [bmarvinb/react-trello-clone#80]
When trying to login through the google ID getting the issue
<img width="960" alt="trllolive bug" src="https://user-images.githubusercontent.com/25453389/133394055-93a83f5e-551b-438d-acc3-d5b3120ef55b.png">
 please refer to the below screenshot

**Comment by bmarvinb** [comment]
Try to update page, its issue with hosting, need to change config for this

**Comment by bmarvinb** [comment]
fixed
