### ISSUE TITLE
docker eslint error

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/react-trello-clone#81]

**Comment by bmarvinb** [comment]
@ashu-11 here the ticket

**Comment by ashu-11** [comment]
please assign it to me

**Comment by bmarvinb** [comment]
@ashu-11 ready

**Comment by cyntler** [comment]
@bmarvinb https://github.com/bmarvinb/react-trello-clone/pull/82/files - fix probably.

**Comment by bmarvinb** [comment]
@cyntler will check it today

**Comment by bmarvinb** [comment]
@cyntler the same error

**Comment by bmarvinb** [comment]
@ashu-11 do you have any progress?

**Comment by ashu-11** [comment]
yes issue resolved but when trying to push geeting :
remote: Permission to bmarvinb/react-trello-clone.git denied to ashu-11.
fatal: unable to access 'https://github.com/bmarvinb/react-trello-clone.git/': The requested URL returned error: 403

**Comment by bmarvinb** [comment]
@ashu-11 I think the problem is not is repo, but in your local setup

**Comment by bmarvinb** [comment]
@ashu-11 please try to use these steps
1. fork the repo
2. clone new repo with https
3. create new branch from master
4. push this branch
5. then you will find "create pull request" in your github

**Comment by bmarvinb** [comment]
@cyntler fixed it, closed
