### ISSUE TITLE
Bug. Landing page

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/react-trello-clone#96]
![image](https://user-images.githubusercontent.com/23120972/135416903-b2a5a584-8b1d-4155-b56b-ab9e65ff7996.png)

When user is logged in, and he trying to open '/' or landing page, he should be redirected to 'boards' page

**Comment by bmarvinb** [comment]
@RanjithSivam hello, can you look at this issue please?

**Comment by RanjithSivam** [comment]
@bmarvinb done
